### ISSUE TITLE
Implement fit/predict to support iterators

### ISSUE THREAD

**Issue by ilblackdragon** [tensorflow/skflow#7]
Many datasets can't fit into memory, and TF doesn't actually requires the whole dataset in the memory.
Instead of loading the dataset into memory, it's possible to stream it using iterators and feed data that way. 

Fit/predict functions in Estimators should be able to take X and y as iterators and read from them while processing data.

**Comment by mth4saurabh** [comment]
@ilblackdragon Hi, do you mean to implement something similar to `partial_fit` (in scikit-learn)?

**Comment by ilblackdragon** [comment]
@mth4saurabh I just realized, I actually implemented partial_fit in the fit right now (see examples/text_classification.py it does partial fit in the loop with evaluation in between).

I think sklearn default interface is that fit() restarts the learning, but given that constructing new Estimator is so easy and partial fit is pretty much super important for DL, I think the way it works right will do.

**Comment by vinhqdang** [comment]
I think it would be great

I am working with CNN and RNN for text classification,

For instance, with CNN, when I increased EMBEDDING_SIZE value, I see the error ``Killed: 9`` when I run my program. Since I did not change anything else, it would be a consequence of increasing EMBEDDING_SIZE

Same, if I increase ``MAX_DOCUMENT_LENGTH`` to 5000 for instance, the problem appears ...

**Comment by michael4john** [comment]
I think the problem I encountered has something to do with the topic discussed here. If it is inappropriate for me to comment/post here, please direct me to somewhere else.

I was trying to run the text_classification.py file, but with my own data. But I got the following error message from the stdin:

> Total words: 4306
I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op parallelism threads: 4
I tensorflow/core/common_runtime/direct_session.cc:58] Direct session inter op parallelism threads: 4
Step #1, avg. loss: 2.17322
W tensorflow/core/common_runtime/executor.cc:1076] 0x2be2420 Compute status: Invalid argument: Index 4306 at offset 90 in Tindices is out of range
         [[Node: words/embedding_lookup/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](words/words_embeddings/read, words/embedding_lookup/Reshape)]]
Traceback (most recent call last):
  File "search_classification.py", line 86, in <module>
    classifier.fit(X_train, y_train, logdir='/tmp/tf_examples/word_rnn')
  File "/home/fz1662/skflow/estimators/base.py", line 214, in fit
    feed_params_fn=self._data_feeder.get_feed_params)
  File "/home/fz1662/skflow/trainer.py", line 147, in train
    feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 368, in run
    results = self._do_run(target_list, unique_fetch_targets, feed_dict_string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 444, in _do_run
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: Index 4306 at offset 90 in Tindices is out of range
         [[Node: words/embedding_lookup/embedding_lookup = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](words/words_embeddings/read, words/embedding_lookup/Reshape)]]
Caused by op u'words/embedding_lookup/embedding_lookup', defined at:
  File "search_classification.py", line 86, in <module>
    classifier.fit(X_train, y_train, logdir='/tmp/tf_examples/word_rnn')
  File "/home/fz1662/skflow/estimators/base.py", line 188, in fit
    self._setup_training()
  File "/home/fz1662/skflow/estimators/base.py", line 127, in _setup_training
    self._inp, self._out)
  File "search_classification.py", line 67, in rnn_model
    embedding_size=EMBEDDING_SIZE, name='words')
  File "/home/fz1662/skflow/ops/embeddings_ops.py", line 77, in categorical_variable
    return embedding_lookup(embeddings, tensor_in)
  File "/home/fz1662/skflow/ops/embeddings_ops.py", line 50, in embedding_lookup
    embeds_flat = tf.nn.embedding_lookup(params, ids_flat, name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/embedding_ops.py", line 82, in embedding_lookup
    return array_ops.gather(params[0], ids, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 302, in gather
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 664, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1834, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1043, in __init__
    self._traceback = _extract_stack()

I tried searching on the Internet, but without any luck finding even a potential solution. By reading the error messages several times, I assume this should be related to the dataset by itself. The attached zipped file include the train and test datasets, and the python files with minor modifications.

[search.zip](https://github.com/tensorflow/skflow/files/110349/search.zip)

The python version I used to run the code is 2.7. The sql query file, which generated the two datasets, is also included.

Any advices will be greatly appreciated.

**Comment by ilblackdragon** [comment]
Hi,

This error indeed is connected to dataset, but not this issue specifically.

The "*tensorflow.python.framework.errors.InvalidArgumentError: Index 4306
at offset 90 in Tindices is out of range" *means
that there is an index in the data that is outside of range of number of
embeddings you've allocated.

Given that number of words is 4306 it's quiet strange, but I would
recommend to add +1 in
https://github.com/tensorflow/skflow/blob/master/examples/text_classification.py#L50
to n_words and see if that helps.

On Fri, Jan 29, 2016 at 12:13 PM, michael4john <notifications@github.com>
wrote:

> I think the problem I encountered has something to do with the topic
> discussed here. If it is inappropriate for me to comment/post here, please
> direct me to somewhere else.
>
> I was trying to run the text_classification.py file, but with my own data.
> But I got the following error message from the stdin:
>
> Total words: 4306
> I tensorflow/core/common_runtime/local_device.cc:40] Local device intra op
> parallelism threads: 4
> I tensorflow/core/common_runtime/direct_session.cc:58] Direct session
> inter op parallelism threads: 4
> Step #1 <https://github.com/tensorflow/skflow/pull/1>, avg. loss: 2.17322
> W tensorflow/core/common_runtime/executor.cc:1076] 0x2be2420 Compute
> status: Invalid argument: Index 4306 at offset 90 in Tindices is out of
> range
> [[Node: words/embedding_lookup/embedding_lookup = GatherTindices=DT_INT64,
> Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"
> <http://words/words_embeddings/read,%20words/embedding_lookup/Reshape>]]
> Traceback (most recent call last):
> File "search_classification.py", line 86, in
> classifier.fit(X_train, y_train, logdir='/tmp/tf_examples/word_rnn')
> File "/home/fz1662/skflow/estimators/base.py", line 214, in fit
> feed_params_fn=self.
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> *data_feeder.get_feed_params) File "/home/fz1662/skflow/trainer.py", line
> 147, in train feed_dict=feed_dict) File
> "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py",
> line 368, in run results = self.do_run(target_list, unique_fetch_targets,
> feed_dict_string) File
> "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py",
> line 444, in _do_run e.code)
> tensorflow.python.framework.errors.InvalidArgumentError: Index 4306 at
> offset 90 in Tindices is out of range [[Node:
> words/embedding_lookup/embedding_lookup = GatherTindices=DT_INT64,
> Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"
> <http://words/words_embeddings/read,%20words/embedding_lookup/Reshape>]]
> Caused by op u'words/embedding_lookup/embedding_lookup', defined at: File
> "search_classification.py", line 86, in classifier.fit(X_train, y_train,
> logdir='/tmp/tf_examples/word_rnn') File
> "/home/fz1662/skflow/estimators/base.py", line 188, in fit
> self._setup_training() File "/home/fz1662/skflow/estimators/base.py", line
> 127, in _setup_training self._inp, self._out) File
> "search_classification.py", line 67, in rnn_model
> embedding_size=EMBEDDING_SIZE, name='words') File
> "/home/fz1662/skflow/ops/embeddings_ops.py", line 77, in
> categorical_variable return embedding_lookup(embeddings, tensor_in) File
> "/home/fz1662/skflow/ops/embeddings_ops.py", line 50, in embedding_lookup
> embeds_flat = tf.nn.embedding_lookup(params, ids_flat, name) File
> "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/embedding_ops.py",
> line 82, in embedding_lookup return array_ops.gather(params[0], ids,
> name=name) File
> "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py",
> line 302, in gather name=name) File
> "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py",
> line 664, in apply_op op_def=op_def) File
> "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py",
> line 1834, in create_op original_op=self._default_original_op,
> op_def=op_def) File
> "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py",
> line 1043, in __init*
> self._traceback = _extract_stack()
>
> I tried searching on the Internet, but without any luck finding even a
> potential solution. By reading the error messages several times, I assume
> this should be related to the dataset by itself. The attached zipped file
> include the train and test datasets, and the python files with minor
> modifications.
>
> search.zip <https://github.com/tensorflow/skflow/files/110349/search.zip>
>
> The python version I used to run the code is 2.7. The sql query file,
> which generated the two datasets, is also included.
>
> Any advices will be greatly appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tensorflow/skflow/issues/7#issuecomment-176949911>.
>



-- 
Best regards,
Illia Polosukhin

**Comment by ilblackdragon** [comment]
Closing this and the iterator processing is implemented. Neural translation example is a demo of that.
